name: "Git Action for Python script"
on: [push, pull_request]
jobs:
    build:
        name: Run the python Script
        runs-on: ubuntu-latest
        steps:
            - name: "Running Python script"
              uses: actions/checkout@v1
            - name: "Run python_run"
              uses: ./python_run
              with:
                arg1: "sdariza"